services:
  pg:
    image: postgres:17.5
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 2s
      retries: 3

  tasks_app:
    build:
      dockerfile: Dockerfile
      context: .

    env_file:
      - .env

#    command: gunicorn config.wsgi.application --bind 0.0.0.0:8000

    ports:
      - "8000:8000"

    depends_on:
      pg:
        condition: service_healthy

    volumes:
      - ./staticfiles:/var/app/static
#      - ./media:/var/app/media
#
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
#      - "443:443"
    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./media:/media:ro
      - ./staticfiles:/staticfiles:ro
    depends_on:
      - tasks_app

volumes:
  pgdata: