# Generated by Django 5.2.4 on 2025-07-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="under_his_command",
        ),
        migrations.AddField(
            model_name="customuser",
            name="company",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Наименование компании",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(max_length=150, verbose_name="Должность"),
        ),
    ]
