# Generated by Django 5.2.4 on 2025-07-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "В работе"),
                    ("COMPLETED", "Завершена"),
                    ("PENDING", "Ожидание"),
                    ("CANCELLED", "Отменена"),
                ],
                default="PENDING",
                verbose_name="Статус задачи",
            ),
        ),
    ]
