# Generated by Django 5.2.4 on 2025-07-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0003_task_created_at_task_updated_at_task_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="child_tasks",
            field=models.ManyToManyField(
                blank=True, to="task_app.task", verbose_name="Подзадача"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="task_app.task",
                verbose_name="Главная задача",
            ),
        ),
    ]
