# Generated by Django 5.2.4 on 2025-07-23 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0004_task_child_tasks_task_parent_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="child_tasks",
        ),
        migrations.AlterField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="parent_tasks",
                to="task_app.task",
                verbose_name="Главная задача",
            ),
        ),
    ]
