# Generated by Django 5.2.4 on 2025-07-23 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0005_remove_task_child_tasks_alter_task_parent_task"),
        ("user_app", "0003_company_alter_customuser_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="user_app.company",
                verbose_name="Компания",
            ),
        ),
    ]
