# Generated by Django 5.2.4 on 2025-08-20 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0006_task_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Крайний срок"
            ),
        ),
    ]
